### ISSUE TITLE
ARM 32/64-bit support

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-secp256k1#16]
The current config hardcode for x86_64: https://github.com/status-im/nim-secp256k1/blob/85b2620a6e4c41eaa4caa378bd70902cff5a1c48/secp256k1_wrapper/libsecp256k1-config.h

We also need to build for x86_32, ARM32 and ARM64

**Comment by stefantalpalaru** [comment]
> The current config hardcode for x86_64

What do you mean? It's conditional, based on architecture-specific C preprocessor defines: https://github.com/status-im/nim-secp256k1/blob/85b2620a6e4c41eaa4caa378bd70902cff5a1c48/secp256k1_wrapper/libsecp256k1-config.h#L63

**Comment by mratsim** [comment]
Yes, actually the config file seems to be informative and not enforcing anything during compilation
