### ISSUE TITLE
Build error - Error: undeclared identifier: 'csize_t'`

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-secp256k1#20]
## Problem

Running `git submodule update --init` and `nimble test` in `nim-secp256k1` at latest (https://github.com/status-im/nim-secp256k1/commit/5af866754b5f17c49e1a1f7f90f2fd0c235eee99) results in error `/home/oskarth/git/status-im/nim-secp256k1/secp256k1.nim(105, 9) Error: undeclared identifier: 'csize_t'`.

## Workaround

If  I checkout `HEAD~1` `nimble test` works.

## Notes

I also notice that if I do `git submodule update` and run  `./gen.sh` in the wrapper that `secp256k1_wrapper/libsecp256k1-config.h` changes a bit (nothing major from what I can tell tho)

First encountered when building `nim-libp2p`. I tried clearing cache at `~/.cache/nim` but I might be missing some other cache or submodule update command.

**Comment by jangko** [comment]
`csize_t` is introduced in Nim 1.2.0
probably your Nim compiler is outdated.

**Comment by oskarth** [comment]
Gotcha, it works now. Thanks
