### ISSUE TITLE
Nimble warning: incorrect structure

### ISSUE THREAD

**Issue by markspanbroek** [status-im/nim-secp256k1#31]
When including secp256k1 as a dependency in nimble, I get the following warning:

```
  Warning: Package 'secp256k1' has an incorrect structure. The top level of the
package source directory should contain at most one module, named
'secp256k1.nim', but a file named 'secp256k1_abi.nim' was found. This will be an
error in the future.
      Hint: If this is the primary source file in the package, rename it to secp256k1.nim'. 
If it's a source file required by the main module, or if it is one of several modules 
exposed by 'secp256k1', then move it into a 'secp256k1/' subdirectory. If it's a test
file or otherwise not required to build the the package 'secp256k1.nim', prevent its
installation by adding `skipFiles = @["secp256k1_abi.nim"]` to the .nimble file. See
https://github.com/nim-lang/nimble#libraries for more info.
```

**Comment by mratsim** [comment]
Nimble is overly pedantic here.

Until this is solved https://github.com/nim-lang/nimble/issues/653 and nimble allows lockfiles https://github.com/nim-lang/nimble/issues/127 and we can move away from submodules there is no reason to try to solve this problem.

External users can install the library as well so it's non-blocking there.

**Comment by markspanbroek** [comment]
Yes, it's indeed not blocking. But it's also annoying :)
If I were to create a small PR to fix the warning, would you accept it?
