### ISSUE TITLE
bug: Compilation error on new AMD platform

### ISSUE THREAD

**Issue by NagyZoltanPeter** [status-im/nim-secp256k1#56]
While building nim-waku we faced an issue compiling secp256k1 on a new AMD Ryzen 7 PRO 7840U system (on UBUNTU 22.04 LTS)
https://github.com/waku-org/nwaku/issues/2560

_originally reported from outside_

I would like to propose a quick workaround until it maybe fixed in the upstream library, otherwise please advise.
[patch: amd-asm-compilation-fix](https://github.com/status-im/nim-secp256k1/files/14929771/amd-asm-compilation-fix.patch.txt)

**Comment by mratsim** [comment]
Can you check with Clang?

Also can you ensure that LTO is not used for crypto: https://github.com/status-im/nimbus-eth2/blob/dc19b08/config.nims#L220-L221

You might also want to ensure you have enough register by passing `-fomit-frame-pointer` to secp256k1 building. 
Cryptographic libraries need all the registers they can get, and not passing this will incure a large performance penalty:

https://www.phoronix.com/review/fedora-frame-pointer/2

![image](https://github.com/status-im/nim-secp256k1/assets/22738317/dbad01a6-b872-46df-9744-4ae4e9b5314c)

**Comment by NagyZoltanPeter** [comment]
> Can you check with Clang?
> 
> Also can you ensure that LTO is not used for crypto: https://github.com/status-im/nimbus-eth2/blob/dc19b08/config.nims#L220-L221, as if there is inlining, the compiler might run out of registers.
> 
> You might also want to ensure you have enough register by passing `-fomit-frame-pointer` to secp256k1 building. Cryptographic libraries need all the registers they can get, and not passing this will incure a large performance penalty:
> 
> https://www.phoronix.com/review/fedora-frame-pointer/2
> 
> ![image](https://private-user-images.githubusercontent.com/22738317/321930171-dbad01a6-b872-46df-9744-4ae4e9b5314c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTM0MzcsIm5iZiI6MTcxMjkxMzEzNywicGF0aCI6Ii8yMjczODMxNy8zMjE5MzAxNzEtZGJhZDAxYTYtYjg3Mi00NmRmLTk3NDQtNGFlNGU5YjUzMTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA5MTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNjAwMTJiYzYzZmY3ZGNjMGE4OGMxYWVjYWJkYTFmYjA2MzhkYjBjZmZjNDY5Njg2MTg2ODk3YWFjMzhmN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F_uCLZNQoyjasNb-tYw2Byhfpg7yP_0pOjwKNeVxLig)

Certainly, but it may not help find out the issue.
I have no access to that type of AMD cpu powered machine that produced the error we faced. My colleague has that one. On my Intel with gcc 12 on Ubuntu I can compile even the asm inline part, tests are just seems fine.
Also another issue that in nim-waku we compilee with gcc so even clang would compile it it may not help.
What I can do in addition to this workaround to point our dependency to a separate branch here and thus to avoid main line would have this forced avoid of that specific asm inline code.
But I'm curious if other project depending on this version of nim-secp256k1 - I suppose - would fail to compile in similar cirtumstances.

**Comment by tersec** [comment]
Oppose this "quick workaround" from landing in this library. It would come with visible perf regressions for `nimbus-eth2`.

**Comment by tersec** [comment]
> Certainly, but it may not help find out the issue. I have no access to that type of AMD cpu powered machine that produced the error we faced. My colleague has that one.

This should be reproducible by specifying the correct `-march` flags to the correct `gcc` version (which has been specified above), even if one doesn't have said CPU, as it will "cross-compile" of sorts regardless.

**Comment by NagyZoltanPeter** [comment]
Thanks for the tips. I accept the perf concerns. 
Will try to come back with more proper analysis and/or issue a ticket of possible on the vendor repo.
I'm not sure about nimbus, but waku supposed to be run on different platforms, hence the workaround till can have fix. So I can imagine a solution we can use that does not influence other users.

**Comment by mratsim** [comment]
> Certainly, but it may not help find out the issue.
> I have no access to that type of AMD cpu powered machine that produced the error we faced. My colleague has that one. On my Intel with gcc 12 on Ubuntu I can compile even the asm inline part, tests are just seems fine.

The issue is about "error: ‘asm’ operand has impossible constraints" which means that GCC fails to find enough registers. If you compile with Clang and it fails you will have a better error message.

Every step, I outline will help you pinpoint the issue, this is something I dealt with on a regular basis:
remove this `-fomit-frame-pointer` from my assembly code and the compiler will throw the "impossible constraints" error: https://github.com/mratsim/constantine/blob/976c8bb/constantine/math/arithmetic/assembly/limbs_asm_modular_x86.nim#L23-L24

Also the issue is not AMD specific, you need the same Ubuntu version, Ubuntu changed the defaults of GCC on 24.04. If your colleague is using a preview version, it's normal they have the issue and not you.

https://www.phoronix.com/forums/forum/software/distributions/1428123-ubuntu-24-04-lts-to-enable-frame-pointers-by-default-for-better-profiling-debugging

**Comment by tersec** [comment]
@mratsim `nimbus-eth2` [explicitly enables frame pointers](https://github.com/status-im/nimbus-eth2/blob/d2a07514541ffe6ee02a2ec7272ce7a315131e04/config.nims#L132-L135):
```nim
# omitting frame pointers in nim breaks the GC
# https://github.com/nim-lang/Nim/issues/10625
switch("passC", "-fno-omit-frame-pointer")
switch("passL", "-fno-omit-frame-pointer")
```
to work around another Nim issue.

**Comment by mratsim** [comment]
Confirmed upstream, the library should be compiled with `-fomit-frame-pointer` otherwise GCC runs out of registers: https://github.com/bitcoin-core/secp256k1/pull/846#issue-739202153

**Comment by tersec** [comment]
- https://github.com/bitcoin-core/secp256k1/issues/1623
